apiVersion: v1
kind: Pod
metadata:
  name: avg-speed-calculator
  labels:
    app: avg-speed-calculator
    version: v1
spec:
  containers:
    - name: avg-speed-app
      image: amirdirin/lectdemo5_2026:latest
      imagePullPolicy: Always
      stdin: true
      tty: true
      resources:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "256Mi"
          cpu: "200m"