sonar.projectKey= avg_consol
sonar.projectName=avgspd12
sonar.projectVersion=1.0
sonar.sources=src
sonar.java.binaries=target/classes
sonar.host.url=http://localhost:9000

# run with:
#    mvn clean verify sonar:sonar "-Dsonar.projectKey=untitled" "-Dsonar.token=$env:SONAR_TOKEN" "-Dsonar.host.url=http://localhost:9000"